### ISSUE TITLE
Add to awesome-dpsg list

### ISSUE THREAD

**Issue by mstoetzer** [f1shl/nami-beitragsrechner#5]
Hi, ich möchte Dein Repo gerne in die awesome-dpsg Liste aufnehmen: https://github.com/mstoetzer/awesome-dpsg

**Comment by f1shl** [comment]
Hey,

Ja klar, kannst du gerne hinzufügen.

LG

**Comment by mstoetzer** [comment]
Cool! Gerne auch weiterverteilen oder selbst was hinzufügen, wenn dir was einfällt :)

**Comment by BenjoNX** [comment]
I developed a soft based that could generate a xml sepa file just with a copy/paste on a google sheet [sepaxml.com](https://www.sepaxml.com) available in multi-language
